name: PR Sentry ID Lint
on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
    - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: "./"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
